global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus kendini monitörleme
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter - sistem metrikleri
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor - container metrikleri
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # PostgreSQL Exporter - veritabanı metrikleri
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Uygulama metrikleri (eğer uygulamanız metrics endpoint'i varsa)
  - job_name: "insider-api"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s
