{
 "title": "Cadvisor exporter",
 "description": "Simple exporter for cadvisor only",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{instance=\"cadvisor:8080\",id=~\"/docker/.*\"}[5m])) by (id) *100, \"short_id\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\")",
     "legendFormat": "{{short_id}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{instance=\"cadvisor:8080\",id=~\"/docker/.*\"}) by (id), \"short_id\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\")",
     "legendFormat": "{{short_id}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_cache{instance=\"cadvisor:8080\",id=~\"/docker/.*\"}) by (id), \"short_id\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\")",
     "legendFormat": "{{short_id}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Received Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"cadvisor:8080\"}[5m])) by (interface)",
     "legendFormat": "{{interface}} - receive"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"cadvisor:8080\"}[5m])) by (interface)",
     "legendFormat": "{{interface}} - transmit"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "up{job=\"cadvisor\"}",
     "legendFormat": "cAdvisor Status"
    }
   ]
  }
 ]
}