CREATE TABLE IF NOT EXISTS balances (
    user_id INTEGER PRIMARY KEY,
    amount REAL NOT NULL DEFAULT 0,
    last_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
